apps/pmp-web/src/index.html

feat(pmp): add web app title in index.html

---

.sgcrc
package-lock.json
package.json

feat(pmp): add sgc plugin for commit messages

---

apps/pmp-web/src/app/app.module.ts
apps/pmp-web/src/index.html
apps/pmp-web/src/styles.scss
package-lock.json
package.json

feat(pmp): add Angular Material

---

libs/pmp-api/api-service/repository/data-access/src/lib/interceptors/github-auth.interceptor.ts
libs/pmp-api/api-service/repository/data-access/src/lib/pmp-api-api-service-repository-data-access.module.ts
libs/pmp-api/api-service/repository/data-access/src/lib/repositories/pr.data-service.ts
libs/pmp-api/api-service/repository/data-access/src/lib/repositories/repository.data-service.ts

refactor(pmp-api): add interceptor for github auth

---

angular.json
libs/pmp-web/repository/shell/README.md
libs/pmp-web/repository/shell/jest.config.js
libs/pmp-web/repository/shell/src/index.ts
libs/pmp-web/repository/shell/src/lib/pmp-web-repository-shell.module.spec.ts
libs/pmp-web/repository/shell/src/lib/pmp-web-repository-shell.module.ts
libs/pmp-web/repository/shell/src/lib/shell-routing.module.ts
libs/pmp-web/repository/shell/src/test-setup.ts
libs/pmp-web/repository/shell/tsconfig.json
libs/pmp-web/repository/shell/tsconfig.lib.json
libs/pmp-web/repository/shell/tsconfig.spec.json
libs/pmp-web/repository/shell/tslint.json
libs/pmp-web/repository/users/shell/README.md
libs/pmp-web/repository/users/shell/jest.config.js
libs/pmp-web/repository/users/shell/src/index.ts
libs/pmp-web/repository/users/shell/src/lib/pmp-web-repository-users-shell.module.spec.ts
libs/pmp-web/repository/users/shell/src/lib/pmp-web-repository-users-shell.module.ts
libs/pmp-web/repository/users/shell/src/lib/shell-routing.module.ts
libs/pmp-web/repository/users/shell/src/test-setup.ts
libs/pmp-web/repository/users/shell/tsconfig.json
libs/pmp-web/repository/users/shell/tsconfig.lib.json
libs/pmp-web/repository/users/shell/tsconfig.spec.json
libs/pmp-web/repository/users/shell/tslint.json
libs/pmp-web/shell/src/lib/shell-routing.module.ts
nx.json
tsconfig.json
tslint.json

feat(pmp-web): basic routing for repository users

---

angular.json
libs/pmp-web/shell/src/lib/shell-routing.module.ts
libs/pmp-web/users/shell/README.md
libs/pmp-web/users/shell/jest.config.js
libs/pmp-web/users/shell/src/index.ts
libs/pmp-web/users/shell/src/lib/pmp-web-users-shell.module.spec.ts
libs/pmp-web/users/shell/src/lib/pmp-web-users-shell.module.ts
libs/pmp-web/users/shell/src/lib/shell-routing.module.ts
libs/pmp-web/users/shell/src/test-setup.ts
libs/pmp-web/users/shell/tsconfig.json
libs/pmp-web/users/shell/tsconfig.lib.json
libs/pmp-web/users/shell/tsconfig.spec.json
libs/pmp-web/users/shell/tslint.json
nx.json
tsconfig.json
tslint.json

feat(pmp-web): basic routing for displaying user statistics

---

angular.json
libs/pmp-web/user/shell/src/lib/containers/user/user.component.scss
libs/pmp-web/user/shell/src/lib/shell-routing.module.ts
libs/pmp-web/user/users-statistics/feature/README.md
libs/pmp-web/user/users-statistics/feature/jest.config.js
libs/pmp-web/user/users-statistics/feature/src/index.ts
libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.html
libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.scss
libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.ts
libs/pmp-web/user/users-statistics/feature/src/lib/pmp-web-user-users-statistics-feature.module.spec.ts
libs/pmp-web/user/users-statistics/feature/src/lib/pmp-web-user-users-statistics-feature.module.ts
libs/pmp-web/user/users-statistics/feature/src/lib/pmp-web-user-users-statistics-routing.module.ts
libs/pmp-web/user/users-statistics/feature/src/test-setup.ts
libs/pmp-web/user/users-statistics/feature/tsconfig.json
libs/pmp-web/user/users-statistics/feature/tsconfig.lib.json
libs/pmp-web/user/users-statistics/feature/tsconfig.spec.json
libs/pmp-web/user/users-statistics/feature/tslint.json
libs/shared/domain/src/index.ts
libs/shared/domain/src/lib/models/user-statistics.read-model.ts
nx.json
tsconfig.json
tslint.json

Add library users statistics feature.
Add users statistics component with base logic.
refs #18

feat(pmp-web): users statistics feature

---

apps/pmp-api/tsconfig.app.json
libs/pmp-api/api-service/repository/api/src/lib/controllers/repository.controller.ts
libs/pmp-api/api-service/repository/core/src/lib/pmp-api-api-service-repository-core.module.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/get-user-prs.query.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/get-user-prs.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repositories.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repository-users.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-users.query.ts
libs/pmp-api/api-service/repository/core/src/lib/repository.facade.ts
libs/pmp-api/api-service/repository/core/src/lib/services/prs.service.ts
libs/pmp-api/api-service/repository/core/tsconfig.json
libs/pmp-api/api-service/repository/data-access/src/lib/domain/entities/github-pr.entity.ts
libs/pmp-api/api-service/repository/data-access/src/lib/domain/entities/github-user.entity.ts
libs/pmp-api/api-service/repository/data-access/src/lib/mappers/github-pr.mapper.ts
libs/pmp-api/api-service/repository/data-access/src/lib/mappers/github-user.mapper.ts
libs/pmp-api/api-service/repository/data-access/src/lib/repositories/repository.data-service.ts
libs/pmp-api/api-service/repository/domain/src/index.ts
libs/pmp-api/api-service/repository/domain/src/lib/models/pr.model.ts
libs/pmp-api/api-service/repository/domain/src/lib/models/user.model.ts
libs/pmp-api/api-service/repository/domain/src/lib/read-models/base-repository-statistics.read-model.ts
libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-statistics.read-model.ts
libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-user-statistics.read-model.ts
libs/shared/domain/src/index.ts
libs/shared/domain/src/lib/responses/list-repository-users.response.ts

feat(pmp-api): endpoint for getting users statistics

---

libs/pmp-api/api-service/repository/api/src/lib/controllers/repository.controller.ts
libs/pmp-api/api-service/repository/core/src/lib/pmp-api-api-service-repository-core.module.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/base-list-repository-users.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repository-contributors.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repository-reviewers.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-contributors.query.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-reviewers.query.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-users.query.ts
libs/pmp-api/api-service/repository/core/src/lib/repository.facade.ts
libs/pmp-api/api-service/repository/data-access/src/lib/repositories/pr.data-service.ts
libs/pmp-api/api-service/repository/data-access/src/lib/repositories/repository.data-service.ts
libs/pmp-api/api-service/repository/data-access/tsconfig.json

Refactor endpoint for getting users to return repository contributors.
Needed for #17

feat(pmp-api): add endpoint for getting reviewers statistics

---

libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repository-reviewers.handler.ts
libs/pmp-api/api-service/repository/data-access/src/lib/domain/entities/github-user.entity.ts
libs/pmp-api/api-service/repository/data-access/src/lib/domain/interfaces/user-model-with-pr.interface.ts
libs/pmp-api/api-service/repository/data-access/src/lib/mappers/custom-user-with-pr.mapper.ts
libs/pmp-api/api-service/repository/data-access/src/lib/repositories/repository.data-service.ts
libs/pmp-api/api-service/repository/domain/src/lib/models/user.model.ts
libs/pmp-api/api-service/repository/domain/src/lib/read-models/pr-with-changes.read-model.ts
libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-user-statistics.read-model.ts

Get reviewers of every PR in GitHub, instead of reviewers PRs.
References #17

fix(pmp-api): get repository reviewers

---

libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-user-statistics.read-model.ts
libs/pmp-web/shared/domain/src/lib/interfaces/column.config.ts
libs/pmp-web/shared/domain/src/lib/interfaces/table-config.interface.ts
libs/pmp-web/shared/ui-table/src/lib/components/table/table.component.html
libs/pmp-web/shared/ui-table/src/lib/components/table/table.component.scss
libs/pmp-web/shared/ui-table/src/lib/components/table/table.component.ts
libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.html
libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.scss
libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.ts
libs/shared/domain/src/lib/models/user.statistics.ts

feat(pmp-web): make table component more generic

---

libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-reviewer-statistics.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/services/prs.service.ts
libs/pmp-api/api-service/repository/data-access/src/lib/domain/entities/github-organization.entity.ts
libs/pmp-api/api-service/repository/data-access/src/lib/domain/entities/github-repository.entity.ts
libs/pmp-api/api-service/repository/data-access/src/lib/mappers/github-organization.mapper.ts
libs/pmp-api/api-service/repository/data-access/src/lib/mappers/github-repository.mapper.ts
libs/pmp-api/api-service/repository/domain/src/index.ts
libs/pmp-api/api-service/repository/domain/src/lib/factories/index.ts
libs/pmp-api/api-service/repository/domain/src/lib/factories/repository-prs-statistics-read-model.factory.ts
libs/pmp-api/api-service/repository/domain/src/lib/interfaces/index.ts
libs/pmp-api/api-service/repository/domain/src/lib/interfaces/pr-author.interface.ts
libs/pmp-api/api-service/repository/domain/src/lib/models/base-repository.model.ts
libs/pmp-api/api-service/repository/domain/src/lib/models/index.ts
libs/pmp-api/api-service/repository/domain/src/lib/models/orgranization.model.ts
libs/pmp-api/api-service/repository/domain/src/lib/read-models/pr-statistics.read-model.ts
libs/shared/domain/src/lib/interfaces/pr-author.interface.ts
libs/shared/domain/src/lib/models/pr.statistics.ts
libs/shared/domain/src/lib/models/repository.model.ts

Add missed params for user statistics such as:
- pr id,
- repository picture url
- pr's author picture url, id

fix(pmp-api): needed params for user statistics

---

angular.json
libs/pmp-web/shared/ui-picture-label/src/lib/components/picture-label/picture-label.component.html
libs/pmp-web/shared/ui-picture-label/src/lib/components/picture-label/picture-label.component.ts
libs/pmp-web/user/shell/src/lib/shell-routing.module.ts
libs/pmp-web/user/single-user-statistics/data-access/README.md
libs/pmp-web/user/single-user-statistics/data-access/jest.config.js
libs/pmp-web/user/single-user-statistics/data-access/src/index.ts
libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.actions.ts
libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.effects.ts
libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.facade.ts
libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.reducer.ts
libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.selectors.ts
libs/pmp-web/user/single-user-statistics/data-access/src/lib/pmp-web-user-single-user-statistics-data-access.module.spec.ts
libs/pmp-web/user/single-user-statistics/data-access/src/lib/pmp-web-user-single-user-statistics-data-access.module.ts
libs/pmp-web/user/single-user-statistics/data-access/src/lib/resources/request-payloads/get-single-user-statistics-response.request-payload.ts
libs/pmp-web/user/single-user-statistics/data-access/src/lib/services/single-user-statistics-data.service.ts
libs/pmp-web/user/single-user-statistics/data-access/src/test-setup.ts
libs/pmp-web/user/single-user-statistics/data-access/tsconfig.json
libs/pmp-web/user/single-user-statistics/data-access/tsconfig.lib.json
libs/pmp-web/user/single-user-statistics/data-access/tsconfig.spec.json
libs/pmp-web/user/single-user-statistics/data-access/tslint.json
libs/pmp-web/user/single-user-statistics/feature/src/lib/containers/single-user-statistics/single-user-statistics.component.html
libs/pmp-web/user/single-user-statistics/feature/src/lib/containers/single-user-statistics/single-user-statistics.component.ts
libs/pmp-web/user/single-user-statistics/feature/src/lib/pmp-web-user-single-user-statistics-feature.module.ts
nx.json
tsconfig.json

feat(pmp-web): single user statistic data access

---

libs/pmp-web/user/single-user-statistics/feature/src/lib/components/single-user-statistics-table/single-user-statistics-table.component.html
libs/pmp-web/user/single-user-statistics/feature/src/lib/components/single-user-statistics-table/single-user-statistics-table.component.scss
libs/pmp-web/user/single-user-statistics/feature/src/lib/components/single-user-statistics-table/single-user-statistics-table.component.ts
libs/pmp-web/user/single-user-statistics/feature/src/lib/containers/single-user-statistics/single-user-statistics.component.html
libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.ts
libs/shared/domain/src/lib/models/pr.statistics.ts
libs/shared/domain/src/lib/models/repository.model.ts

Fixed redirect from users to single user statistics.
Fixed redirect from single user statistics to github pr.
Fixed author display name.
Resolve #17

fix(pmp-web): fix redirect and single user ui

---

libs/pmp-api/api-service/repository/api/src/lib/controllers/repository.controller.ts
libs/pmp-api/api-service/repository/api/src/lib/interceptors/response-transform.interceptor.ts
libs/pmp-api/api-service/repository/api/src/lib/requests/list-single-repository.request.ts
libs/pmp-api/api-service/repository/core/src/lib/pmp-api-api-service-repository-core.module.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/get-pr-changes.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/get-repository-prs.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-single-repository.handler.ts
libs/pmp-api/api-service/repository/core/src/lib/queries/list-single-repository.query.ts
libs/pmp-api/api-service/repository/core/src/lib/repository.facade.ts
libs/pmp-api/api-service/repository/data-access/src/lib/interceptors/github-auth.interceptor.ts
libs/pmp-api/api-service/repository/data-access/src/lib/repositories/repository.data-service.ts
libs/pmp-api/shared/config/src/lib/configs/pmp-api-service.config.ts
libs/pmp-api/shared/config/src/lib/pmp-api-shared-config.module.ts
libs/pmp-api/shared/domain/src/lib/base/response.ts
libs/shared/domain/src/lib/requests/index.ts
libs/shared/domain/src/lib/requests/params/list-single-repository.params.ts

feat(pmp-api): get single repository

---

apps/pmp-web/src/assets/styles/_global.scss
apps/pmp-web/src/assets/styles/components/_content-loader.scss
apps/pmp-web/src/styles.scss
libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.component.html
libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.component.ts
libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.presenter.ts
libs/pmp-web/repository/repository-statistics/feature/src/lib/pmp-web-repository-repository-statistics-feature.module.ts
libs/pmp-web/repository/repository-statistics/feature/src/lib/repository-statistics/repository-statistics.component.html
libs/pmp-web/repository/repository-statistics/feature/src/lib/repository-statistics/repository-statistics.component.ts
libs/pmp-web/shared/ui-header-container/src/lib/header-container/header-container.component.ts
libs/pmp-web/shared/ui-statistics-overview-table/src/lib/pmp-web-shared-ui-statistics-overview-table.module.ts
libs/pmp-web/shared/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.html
libs/pmp-web/shared/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.ts
libs/pmp-web/shared/ui-table-pr-statistic/src/lib/pmp-web-shared-ui-table-pr-statistic.module.ts
libs/pmp-web/shared/ui-table-pr-statistic/src/lib/table-pr-statistic/table-pr-statistic.component.html
libs/pmp-web/shared/ui-table-pr-statistic/src/lib/table-pr-statistic/table-pr-statistic.component.ts
libs/pmp-web/user/single-user-statistics/feature/src/lib/containers/single-user-statistics/single-user-statistics.component.html
libs/pmp-web/user/single-user-statistics/feature/src/lib/containers/single-user-statistics/single-user-statistics.component.ts
libs/pmp-web/user/single-user-statistics/feature/src/lib/pmp-web-user-single-user-statistics-feature.module.ts
libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.html
libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.ts
package-lock.json
package.json

Add @ngneat/content-loader library to show facebook-like loading placeholders.
Resolves #96

feat(pmp-web): add loading indicators to all views

---

angular.json
libs/server/repository/api-rest/src/lib/controllers/repository.controller.ts
libs/server/repository/api-rest/src/lib/dtos/add-repository.dto.ts
libs/server/shared/util-repository/README.md
libs/server/shared/util-repository/jest.config.js
libs/server/shared/util-repository/src/index.ts
libs/server/shared/util-repository/src/lib/name-extract/repository-name-extract.util.ts
libs/server/shared/util-repository/tsconfig.json
libs/server/shared/util-repository/tsconfig.lib.json
libs/server/shared/util-repository/tsconfig.spec.json
libs/server/shared/util-repository/tslint.json
nx.json
tsconfig.json
tslint.json

create util files for name extraction

fix(pmp): change fullName to Url in addRepo

---

libs/pmp-web/shared/core/src/lib/configs/github-auth.config.ts
libs/server/auth/infrastructure/src/index.ts
libs/server/auth/infrastructure/src/lib/decorators/credentials.decorator.ts
libs/server/auth/infrastructure/src/lib/guards/auth.guard.ts
libs/server/auth/infrastructure/src/lib/interfaces/request-credentials.interface.ts
libs/server/repository/api-rest/src/lib/controllers/repository.controller.ts
libs/server/repository/api-rest/src/lib/controllers/statistics.controller.ts

Put auth data to req object instead of res object
resolve #PMP-104

fix(pmp-api): fix sending response on private endpoints

---

angular.json
apps/pmp-api/src/app/app.module.ts
libs/server/user/api-rest/README.md
libs/server/user/api-rest/jest.config.js
libs/server/user/api-rest/src/index.ts
libs/server/user/api-rest/src/lib/controllers/user.controller.ts
libs/server/user/api-rest/src/lib/server-user-api-rest.module.ts
libs/server/user/api-rest/tsconfig.json
libs/server/user/api-rest/tsconfig.lib.json
libs/server/user/api-rest/tsconfig.spec.json
libs/server/user/api-rest/tslint.json
libs/server/user/core/application-services/src/index.ts
libs/server/user/core/application-services/src/lib/queries/get-user-info/get-user-info.handler.ts
libs/server/user/core/application-services/src/lib/queries/get-user-info/get-user-info.query.ts
libs/server/user/core/application-services/src/lib/server-user-core-application-services.module.ts
libs/server/user/core/application-services/src/lib/user.facade.ts
nx.json
tsconfig.json

feat(pmp-api): add user-info endpoint

---

libs/pmp-web/auth/feature/src/lib/+state/auth-feature.effects.ts
libs/pmp-web/auth/shell/src/lib/guards/auth.guard.ts
libs/pmp-web/repository/reviewer-statistics/data-access/src/lib/resources/request-payloads/get-reviewer-statistics-response.request-payload.ts
libs/pmp-web/repository/reviewer-statistics/data-access/src/lib/services/reviewer-statistics-data.service.ts
libs/pmp-web/repository/reviewer-statistics/feature/src/lib/containers/reviewer-statistics/reviewer-statistics.component.html
libs/pmp-web/repository/reviewer-statistics/feature/src/lib/containers/reviewer-statistics/reviewer-statistics.component.ts
libs/pmp-web/repository/reviewers-statistics/feature/src/lib/containers/reviewers-statistics/reviewers-statistics.component.html
libs/pmp-web/repository/reviewers-statistics/feature/src/lib/containers/reviewers-statistics/reviewers-statistics.component.ts
libs/pmp-web/repository/shell/src/lib/pmp-web-repository-shell-routing.module.ts
libs/pmp-web/repository/ui-table-pr-statistic/src/lib/pmp-web-repository-ui-table-pr-statistic.module.ts
libs/pmp-web/repository/ui-table-pr-statistic/src/lib/table-pr-statistic/table-pr-statistic.component.html
libs/pmp-web/shared/ui-sidebar/src/lib/components/sidebar/sidebar.component.html
libs/pmp-web/shared/util/src/lib/pipes/resolve-hours.pipe.spec.ts
libs/pmp-web/shared/util/src/lib/pipes/resolve-hours.pipe.ts

bump to previous forked pr since there were problems with merging it

feat(pmp-web): enhance resolveHours pipes behaviour

---

libs/pmp-web/repository/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.scss

fix(pmp-web): Remove gray background from icons

---

libs/pmp-web/auth/shell/src/lib/interceptors/auth-interceptor.ts
libs/shared/domain/src/index.ts
libs/shared/domain/src/lib/enums/http-status-codes.enum.ts

feat(pmp): logout on unauthorized request

---

libs/pmp-web/auth/data-access/src/lib/+state/auth.actions.ts
libs/pmp-web/auth/data-access/src/lib/+state/auth.effects.ts
libs/pmp-web/auth/data-access/src/lib/+state/auth.facade.ts
libs/pmp-web/auth/data-access/src/lib/+state/auth.reducer.ts
libs/pmp-web/auth/data-access/src/lib/+state/auth.selectors.ts
libs/pmp-web/auth/data-access/src/lib/services/auth-data.service.ts
libs/pmp-web/auth/public/src/lib/+state/auth-public.facade.ts
libs/pmp-web/repository/shell/src/lib/containers/repositories/repositories.component.html
libs/pmp-web/repository/shell/src/lib/containers/repositories/repositories.component.ts
libs/pmp-web/shared/ui-navbar/src/lib/components/navbar/navbar.component.html
libs/pmp-web/shared/ui-navbar/src/lib/components/navbar/navbar.component.scss
libs/pmp-web/shared/ui-navbar/src/lib/components/navbar/navbar.component.ts
libs/shared/domain/src/index.ts
libs/shared/domain/src/lib/interfaces/get-user-info-success-payload.ts
libs/shared/domain/src/lib/interfaces/user.interface.ts
libs/shared/domain/src/lib/responses/get-user-info.response.ts

feat(pmp): display user info in navbar

---

libs/pmp-web/repository/shell/src/lib/containers/repositories/repositories.component.scss

fix(front) fix pages' height

---

libs/server/repository/api-rest/src/lib/controllers/repository.controller.ts
libs/server/repository/core/application-services/src/index.ts
libs/server/repository/core/application-services/src/lib/commands/delete-repository/delete-repository.command.ts
libs/server/repository/core/application-services/src/lib/commands/delete-repository/delete-repository.handler.ts
libs/server/repository/core/application-services/src/lib/repository.facade.ts
libs/server/repository/core/application-services/src/lib/server-repository-core-application-services.module.ts
libs/server/repository/core/domain-services/src/lib/repositories/repository.repository.ts
libs/server/repository/infrastructure/src/lib/repositories/repository-repository.adapter.ts

feat(pmp): remove repository - backend

---

angular.json
libs/pmp-web/repository/data-access/src/lib/+state/repository.actions.ts
libs/pmp-web/repository/data-access/src/lib/+state/repository.effects.ts
libs/pmp-web/repository/data-access/src/lib/+state/repository.facade.ts
libs/pmp-web/repository/data-access/src/lib/services/repository-data.service.ts
libs/pmp-web/repository/domain/src/index.ts
libs/pmp-web/repository/domain/src/lib/payloads/delete-repository.payload.ts
libs/pmp-web/repository/repository-settings/feature/src/lib/containers/repository-settings/repository-settings.component.html
libs/pmp-web/repository/repository-settings/feature/src/lib/containers/repository-settings/repository-settings.component.ts
libs/pmp-web/repository/repository-settings/feature/src/lib/pmp-web-repository-repository-settings-feature.module.ts
libs/pmp-web/repository/repository-settings/ui/src/lib/repositories-settings-table/repositories-settings-table.component.html
libs/pmp-web/repository/repository-settings/ui/src/lib/repositories-settings-table/repositories-settings-table.component.scss
libs/pmp-web/repository/repository-settings/ui/src/lib/repositories-settings-table/repositories-settings-table.component.ts
libs/pmp-web/shared/domain/src/index.ts
libs/pmp-web/shared/domain/src/payloads/generic-dialog.payload.ts
libs/pmp-web/shared/ui-generic-dialog/README.md
libs/pmp-web/shared/ui-generic-dialog/jest.config.js
libs/pmp-web/shared/ui-generic-dialog/src/index.ts
libs/pmp-web/shared/ui-generic-dialog/src/lib/components/generic-dialog/generic-dialog.component.html
libs/pmp-web/shared/ui-generic-dialog/src/lib/components/generic-dialog/generic-dialog.component.scss
libs/pmp-web/shared/ui-generic-dialog/src/lib/components/generic-dialog/generic-dialog.component.ts
libs/pmp-web/shared/ui-generic-dialog/src/lib/pmp-web-shared-ui-generic-dialog.module.spec.ts
libs/pmp-web/shared/ui-generic-dialog/src/lib/pmp-web-shared-ui-generic-dialog.module.ts
libs/pmp-web/shared/ui-generic-dialog/src/test-setup.ts
libs/pmp-web/shared/ui-generic-dialog/tsconfig.json
libs/pmp-web/shared/ui-generic-dialog/tsconfig.lib.json
libs/pmp-web/shared/ui-generic-dialog/tsconfig.spec.json
libs/pmp-web/shared/ui-generic-dialog/tslint.json
nx.json
tsconfig.json

feat(pmp): remove repository - front

---

libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.component.html
libs/pmp-web/repository/repository-statistics/feature/src/lib/repository-statistics/repository-statistics.component.html
libs/pmp-web/repository/reviewer-statistics/feature/src/lib/containers/reviewer-statistics/reviewer-statistics.component.html
libs/pmp-web/repository/reviewers-statistics/feature/src/lib/containers/reviewers-statistics/reviewers-statistics.component.html
libs/pmp-web/shared/ui-sidebar/src/lib/components/sidebar/sidebar.component.html
libs/pmp-web/shared/ui-sidebar/src/lib/components/sidebar/sidebar.component.scss
libs/pmp-web/shared/ui-sidebar/src/lib/pmp-web-shared-ui-sidebar.module.ts

fix(pmp-web): add tooltips to the navigation bar items

---

libs/pmp-web/repository/reviewer-statistics/data-access/src/lib/+state/reviewer-statistics.actions.ts
libs/pmp-web/repository/reviewer-statistics/data-access/src/lib/+state/reviewer-statistics.facade.ts
libs/pmp-web/repository/reviewer-statistics/data-access/src/lib/resources/payloads/get-reviewer-statistics.payload.ts
libs/pmp-web/repository/reviewer-statistics/data-access/src/lib/resources/request-payloads/get-reviewer-statistics-response.request-payload.ts
libs/pmp-web/repository/reviewer-statistics/data-access/src/lib/services/reviewer-statistics-data.service.ts
libs/pmp-web/repository/reviewer-statistics/feature/src/lib/containers/reviewer-statistics/reviewer-statistics.component.ts
libs/pmp-web/repository/reviewers-statistics/feature/src/lib/containers/reviewers-statistics/reviewers-statistics.component.ts
libs/pmp-web/repository/shell/src/lib/pmp-web-repository-shell-routing.module.ts
libs/pmp-web/repository/ui-table-pr-statistic/src/lib/table-pr-statistic/table-pr-statistic.component.html
libs/pmp-web/repository/ui-table-pr-statistic/src/lib/table-pr-statistic/table-pr-statistics.presenter.ts
libs/server/repository/api-rest/src/lib/controllers/statistics.controller.ts
libs/server/repository/core/application-services/src/lib/queries/get-reviewer-statistics/get-reviewer-statistics.handler.ts
libs/server/repository/core/application-services/src/lib/queries/get-reviewer-statistics/get-reviewer-statistics.query.ts
libs/server/repository/core/application-services/src/lib/read-models/pr-statistics.read-model.ts
libs/server/repository/core/domain/src/lib/entities/pr.entity.ts
libs/server/repository/infrastructure/src/lib/github/mappers/map-github-pr.ts
libs/server/repository/infrastructure/src/lib/github/repositories/github-reviewer.repository.ts
libs/shared/domain/src/lib/interfaces/pr.statistics.ts

fix(pmp): load reviewer by id

---

libs/pmp-web/auth/login-feature/src/lib/containers/login-page/login-page.component.ts
libs/pmp-web/repository/repository-settings/feature/src/lib/containers/repository-settings/repository-settings.component.html
libs/pmp-web/repository/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.html
libs/pmp-web/repository/ui-table-pr-statistic/src/lib/table-pr-statistic/table-pr-statistic.component.html
libs/pmp-web/shared/util/src/lib/pipes/resolve-hours/resolve-hours.pipe.spec.ts
libs/pmp-web/shared/util/src/lib/pipes/resolve-hours/resolve-hourse.pipe.ts
libs/pmp-web/shared/util/src/lib/pipes/time-ago/time-ago.pipe.spec.ts
libs/pmp-web/shared/util/src/lib/pipes/time-ago/time-ago.pipe.ts
libs/pmp-web/shared/util/src/lib/pmp-web-shared-util.module.ts
libs/shared/domain/src/lib/enums/time-unit.enum.ts

Add time ago and resolve hours pipes.
Hide Constraints tab.
Hide Login by gitlab.

fix(pmp-web): display proper maxWaitingTime

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CODE_OF_CONDUCT.md

style(github): format md files

---

.env-sample
docker-compose.yml

build(pmp): load containers from docker hub

---

.github/PULL_REQUEST_TEMPLATE.md

ci(): pull request template check list

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(): fix env directory in reademe

---

CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```

docs(): clarifies architecture sources

---

.github/workflows/pmp-master.yml
.github/workflows/pmp-pr.yml
package.json

Split base job to smaller jobs to run them parallel.
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
"Base" job takes a long time to resolve and require to run all tests even if the last one fails.
CI of the PR when the whole project is affected takes almost 9 minutes,
We have smaller and more specific jobs.
CI of the PR when the whole project is affected takes 5m 44s.
```
[ ] Yes
[x] No
```

ci(): run multiple jobs parallel

---

libs/server/repository/infrastructure/src/index.ts
libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-repository-namespace.entity.ts
libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-repository-owner.entity.ts
libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-repository.entity.ts
libs/server/repository/infrastructure/src/lib/gitlab/mappers/map-gitlab-repository.ts
libs/server/repository/infrastructure/src/lib/gitlab/repositories/gitlab-repository.repository.ts
libs/server/repository/infrastructure/src/lib/server-repository-infrastructure.module.ts
libs/server/repository/shell/src/lib/factories/remote-repository-repository.factory.ts
libs/server/repository/shell/src/lib/server-repository-shell.module.ts
libs/server/shared/util-repository/src/lib/name-extract/repository-name-extract.util.ts

refs #159
```
[ ] Bugfix
[X] Feature
```
Users can not add repository settings for the Gitlab repos.
Issue Number: #159 
The user is allowed to add repository settings for the Gitlab repo.
```
[ ] Yes
[X] No
```

feat(pmp): allow to add gitlab repo settings.

---

libs/server/repository/infrastructure/src/lib/gitlab/repositories/gitlab-repository.repository.ts

refs #159
```
[X] Bugfix
[ ] Feature
```
Current import of the repository abstract class throw an error.
Issue Number: #159 
Error disappear after changing an import.
```
[ ] Yes
[X] No
```

fix(pmp): invalid import in gitlab-repository

---

libs/server/repository/core/application-services/src/lib/queries/get-reviewer-statistics/get-reviewer-statistics.handler.ts

bugfix(pmp-api): remove empty repositories from reviewer statistics

---

libs/server/repository/infrastructure/src/index.ts
libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-pr-details.entity.ts
libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-pr.entity.ts
libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-repository-owner.entity.ts
libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-user.entity.ts
libs/server/repository/infrastructure/src/lib/gitlab/mappers/map-gitalb-pr.ts
libs/server/repository/infrastructure/src/lib/gitlab/mappers/map-gitlab-repository.ts
libs/server/repository/infrastructure/src/lib/gitlab/mappers/map-gitlab-user.ts
libs/server/repository/infrastructure/src/lib/gitlab/repositories/gitlab-pr.repository.ts
libs/server/repository/infrastructure/src/lib/gitlab/repositories/gitlab-reviewer.repository.ts
libs/server/repository/shell/src/lib/factories/pr-repository.factory.ts
libs/server/repository/shell/src/lib/factories/reviewer-repository.factory.ts
libs/server/repository/shell/src/lib/server-repository-shell.module.ts

refs #159
```
[ ] Bugfix
[X] Feature
```
Information about the MR and reviewer is not displayed for the GitLab repos.
Issue Number: #159 
Information about the MR and reviewer is displayed for the GitLab repos.
```
[ ] Yes
[X] No
```

feat(pmp-api): get info about gitlab repo MR and reviewer

---

libs/server/repository/api-rest/src/lib/interceptors/errors.interceptor.ts
libs/server/repository/infrastructure/src/lib/bitbucket/domain/entities/bitbucket-repository-owner.entity.ts
libs/server/repository/infrastructure/src/lib/bitbucket/mappers/map-bitbucket-repository.ts
libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-pr.repository.ts
libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-repository.repository.ts
libs/server/shared/domain/src/index.ts
libs/server/shared/domain/src/lib/exceptions/core-unprocessable-entity.exception.ts
libs/server/shared/util-exception/src/lib/operators.ts

fix(pmp-api): 500 on statistics if some bitbucket repository has no pull requests

---

CHANGELOG.md
libs/pmp-web/repository/repository-settings/ui/src/lib/repositories-settings-table/repositories-settings-table.component.html
libs/server/repository/core/application-services/src/lib/queries/get-reviewer-statistics/get-reviewer-statistics.handler.ts
libs/server/repository/infrastructure/src/lib/bitbucket/domain/entities/bitbucket-repository-owner.entity.ts
libs/server/repository/infrastructure/src/lib/bitbucket/mappers/map-bitbucket-repository.ts
libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-pr.repository.ts
libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-repository.repository.ts
libs/server/shared/core-api-rest/src/lib/interceptors/errors.interceptor.ts
libs/server/shared/domain/src/index.ts
libs/server/shared/domain/src/lib/exceptions/core-unprocessable-entity.exception.ts
libs/server/shared/util-exception/src/lib/operators.ts
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Ci/release 1.2.x

---

.env-sample
.github/workflows/pmp-master.yml
.github/workflows/pmp-pr.yml
angular.json
libs/server/auth/core/application-services/src/lib/queries/get-access-token.query.ts/get-access-token.handler.ts
libs/server/auth/infrastructure-remote-token-crypto/README.md
libs/server/auth/infrastructure-remote-token-crypto/jest.config.js
libs/server/auth/infrastructure-remote-token-crypto/src/index.ts
libs/server/auth/infrastructure-remote-token-crypto/src/lib/server-auth-infrastructure-remote-token-crypto.module.ts
libs/server/auth/infrastructure-remote-token-crypto/src/lib/server-auth-infrastructure-remote-token-crypto.service.ts
libs/server/auth/infrastructure-remote-token-crypto/tsconfig.json
libs/server/auth/infrastructure-remote-token-crypto/tsconfig.lib.json
libs/server/auth/infrastructure-remote-token-crypto/tsconfig.spec.json
libs/server/auth/infrastructure-remote-token-crypto/tslint.json
libs/server/auth/infrastructure/src/lib/guards/auth.guard.ts
libs/server/auth/port/README.md
libs/server/auth/port/jest.config.js
libs/server/auth/port/src/index.ts
libs/server/auth/port/src/lib/remote-token-crypto.service.ts
libs/server/auth/port/tsconfig.json
libs/server/auth/port/tsconfig.lib.json
libs/server/auth/port/tsconfig.spec.json
libs/server/auth/port/tslint.json
libs/server/auth/shell/src/lib/server-auth-shell.module.ts
libs/server/shared/config/src/lib/pmp-api-config.service.ts
nx.json
tsconfig.json
tslint.json
valueadd-dev.json5

BREAKING CHANGE: new auth environment variables
```
[ ] Bugfix
[x] Feature
```
The user stores in the browser only an encrypted token.
```
[x] Yes
[ ] No
```

feat(security): encrypt remote token in jwt

---

libs/server/repository/infrastructure/src/lib/bitbucket/repositories/bitbucket-repository.repository.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(api-repository): bitbucket owner always unprocessable

---

libs/pmp-web/repository/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.html
libs/pmp-web/repository/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.scss
libs/pmp-web/repository/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.ts
libs/server/repository/core/application-services/src/lib/read-models/base-statistics.read-model.ts
libs/shared/domain/src/lib/interfaces/repository-statistics.interface.ts

New columns:
Reviewers count
Average PR is waiting
Average Code to check
Longest waiting PR
Resolve #214
```
[ ] Bugfix
[x] Feature
```
No information about reviewers count, average PR is waiting, average Code to check, longest waiting PR
Issue Number: [#217 ](https://github.com/valueadd-poland/pimp-my-pr/issues/217)
Added new columns to the table
```
[ ] Yes
[x] No
```

feat(pmp): add columns to repository statistics summary

---

libs/pmp-web/repository/data-access/src/lib/+state/repository.facade.ts
libs/pmp-web/repository/repository-settings/feature/src/lib/containers/add-edit-repository-dialog/add-edit-repository-dialog.component.ts
libs/pmp-web/shared/domain/src/index.ts
libs/pmp-web/shared/domain/src/lib/exceptions/api.exception.ts
libs/server/repository/api-rest/src/lib/controllers/repository.controller.ts
libs/server/repository/core/application-services/src/lib/commands/add-repository/add-repository.handler.ts
libs/server/repository/core/domain/src/index.ts
libs/server/repository/core/domain/src/lib/exceptions/repository-already-exists.ts
libs/server/shared/core-api-rest/src/lib/interceptors/errors.interceptor.ts
libs/server/shared/domain/src/index.ts
libs/server/shared/domain/src/lib/exceptions/core-resource-already-exists.exception.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/valueadd-poland/pimp-my-pr/issues/238
-add validation if a repository exists before adding it in repositories controller,
return 409 if exists
-add 409 code handling in add-repository modal
```
[ ] Yes
[x] No
```

fix(web): add error message when repository is added 2 time

---

angular.json
libs/server/repository/core/application-services/src/lib/commands/add-missing-settings/add-missing-settings.command.ts
libs/server/repository/core/application-services/src/lib/commands/add-missing-settings/add-missing-settings.handler.ts
libs/server/repository/core/application-services/src/lib/queries/get-user-settings/get-user-settings.handler.ts
libs/server/repository/core/application-services/src/lib/server-repository-core-application-services.module.ts
libs/server/repository/core/application-services/src/lib/settings.facade.ts
libs/server/repository/core/domain/src/index.ts
libs/server/repository/core/domain/src/lib/consts/required-user-settings.const.ts
libs/server/repository/core/domain/src/lib/factories/default-setting.factory.ts
libs/server/repository/core/domain/src/lib/utils/generate-stats.util.ts
libs/server/repository/core/domain/src/lib/utils/get-missing-settings.util.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: fix timeline and settings

---

.github/workflows/pmp-pr.yml
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: pmp api e2e

---

libs/pmp-web/repository/repository-settings/feature/src/lib/containers/settings/common-settings/common-settings.service.ts
libs/server/repository/core/application-services/src/lib/events/user-added/user-added.event-handler.ts
libs/server/repository/core/application-services/src/lib/queries/list-reviewers-statistics/list-reviewers-statistics.handler.ts
libs/server/repository/core/application-services/src/lib/queries/list-reviewers-statistics/reviewers-statistics-item-read.model.ts
libs/server/repository/core/application-services/src/lib/read-models/factories/repository-prs-statistics-read-model.factory.ts
libs/server/repository/core/application-services/src/lib/read-models/reviewer-model-with-pr.interface.ts
libs/server/repository/core/domain-services/src/lib/repositories/settings.repository.ts
libs/server/repository/core/domain/src/index.ts
libs/server/repository/core/domain/src/lib/consts/required-user-settings.const.ts
libs/server/repository/core/domain/src/lib/entities/common-settings/max-lines-to-check-setting.entity.ts
libs/server/repository/core/domain/src/lib/factories/common-settings-entity.factory.ts
libs/server/repository/core/domain/src/lib/factories/default-setting.factory.ts
libs/server/repository/infrastructure/src/lib/repositories/settings-repository.adapter.ts
libs/shared/domain/src/lib/types/repository-common-setting.type.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #110
```
[ ] Yes
[x] No
```

feat: add reviewers notifications

---

libs/pmp-web/shared/util-google-analytics/src/lib/google-analytics.service.ts
libs/pmp-web/shell/src/lib/pmp-web-shell.module.ts

Activate page tracking
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(web): google analytics not working
